add_subdirectory (AircraftHud)

OPTION(BUILD_MAP_FEATURES_CONVERTER "Build MapFeaturesConverter")
if (BUILD_MAP_FEATURES_CONVERTER)
	add_subdirectory (MapFeaturesConverter)
endif()

add_subdirectory (SkyboltCommon)
if (BUILD_TESTING)
	add_subdirectory (SkyboltCommonTests)
endif()
add_subdirectory (SkyboltEngine)

if (BUILD_PYTHON_BINDINGS)
	add_subdirectory (SkyboltPythonBindings)
endif()

add_subdirectory (SkyboltEnginePlugins)

if (BUILD_TESTING)
	add_subdirectory (SkyboltEngineTests)
endif()

add_subdirectory (SkyboltSim)
if (BUILD_TESTING)
	add_subdirectory (SkyboltSimTests)
endif()
add_subdirectory (SkyboltVis)
if (BUILD_TESTING)
	add_subdirectory (SkyboltVisTests)
endif()
add_subdirectory (TileMapGenerator)

OPTION(BUILD_WITH_QT "Build with Qt")
if (BUILD_WITH_QT)
	add_subdirectory (SkyboltEngineQt)
	if (BUILD_TESTING)
		add_subdirectory (SkyboltEngineQtTests)
	endif()
endif()
