[project]
name = "skybolt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    # TODO: uv tool install results in much faster launching of the tools
#    "conan>=2.31.1",
#    "mkdocs>=1.6.1",
#    "mkdocs-material>=9.7.7",
#    "mkdocstrings[python]>=1.0.6",
]
