[project]
name = "skybolt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "panel>=1.9.3",
    "plotly>=6.9.0",
    "pyorbital>=1.12.1",
    "scipy>=1.18.0",
]

[dependency-groups]
dev = [
    # TODO: uv tool install results in much faster launching of the tools
#    "conan>=2.31.1",
#    "mkdocs>=1.6.1",
#    "mkdocs-material>=9.7.7",
#    "mkdocstrings[python]>=1.0.6",
]
